language: python
python:
  - '2.7'
  - '3.3'
  - '3.4'
env:
  global:
    - DB=postgres
  matrix:
    - DJANGO=1.6.5
install:
  - pip install -q coverage flake8 Django==$DJANGO
before_script:
  - flake8 .
  - psql -c 'CREATE DATABASE querybuilder;' -U postgres
script:
  - coverage run setup.py test
  - coverage report --fail-under=88
